# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'create_register.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_FormCreateRegister(object):
    def setupUi(self, FormCreateRegister):
        FormCreateRegister.setObjectName("FormCreateRegister")
        FormCreateRegister.resize(406, 281)
        self.verticalLayoutWidget = QtWidgets.QWidget(FormCreateRegister)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(190, 220, 195, 30))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.verticalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_save = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btn_save.setObjectName("btn_save")
        self.horizontalLayout.addWidget(self.btn_save)
        self.btn_cancel = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btn_cancel.setObjectName("btn_cancel")
        self.horizontalLayout.addWidget(self.btn_cancel)
        self.formLayoutWidget = QtWidgets.QWidget(FormCreateRegister)
        self.formLayoutWidget.setGeometry(QtCore.QRect(30, 20, 361, 193))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.lineEdit_username = QtWidgets.QLineEdit(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_username.setFont(font)
        self.lineEdit_username.setReadOnly(False)
        self.lineEdit_username.setObjectName("lineEdit_username")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit_username)
        self.label_2 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.label_3 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.label_4 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.lineEdit_value = QtWidgets.QLineEdit(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_value.setFont(font)
        self.lineEdit_value.setObjectName("lineEdit_value")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.lineEdit_value)
        self.comboBox_attribute = QtWidgets.QComboBox(self.formLayoutWidget)
        self.comboBox_attribute.setObjectName("comboBox_attribute")
        self.comboBox_attribute.addItem("")
        self.comboBox_attribute.addItem("")
        self.comboBox_attribute.addItem("")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.comboBox_attribute)
        self.comboBox_operation = QtWidgets.QComboBox(self.formLayoutWidget)
        self.comboBox_operation.setObjectName("comboBox_operation")
        self.comboBox_operation.addItem("")
        self.comboBox_operation.addItem("")
        self.comboBox_operation.addItem("")
        self.comboBox_operation.addItem("")
        self.comboBox_operation.addItem("")
        self.comboBox_operation.addItem("")
        self.comboBox_operation.addItem("")
        self.comboBox_operation.addItem("")
        self.comboBox_operation.addItem("")
        self.comboBox_operation.addItem("")
        self.comboBox_operation.addItem("")
        self.comboBox_operation.addItem("")
        self.comboBox_operation.addItem("")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.comboBox_operation)
        self.label_message = QtWidgets.QLabel(FormCreateRegister)
        self.label_message.setGeometry(QtCore.QRect(30, 180, 361, 16))
        self.label_message.setText("")
        self.label_message.setObjectName("label_message")

        self.retranslateUi(FormCreateRegister)
        QtCore.QMetaObject.connectSlotsByName(FormCreateRegister)

    def retranslateUi(self, FormCreateRegister):
        _translate = QtCore.QCoreApplication.translate
        FormCreateRegister.setWindowTitle(_translate("FormCreateRegister", "Novo Registro"))
        self.btn_save.setText(_translate("FormCreateRegister", "Salvar"))
        self.btn_cancel.setText(_translate("FormCreateRegister", "Cancelar"))
        self.label.setText(_translate("FormCreateRegister", "Username:"))
        self.label_2.setText(_translate("FormCreateRegister", "Attribute: "))
        self.label_3.setText(_translate("FormCreateRegister", "Operation: "))
        self.label_4.setText(_translate("FormCreateRegister", "Value: "))
        self.comboBox_attribute.setItemText(0, _translate("FormCreateRegister", "Mikrotik-Rate-Limit"))
        self.comboBox_attribute.setItemText(1, _translate("FormCreateRegister", "Framed-IP-Address"))
        self.comboBox_attribute.setItemText(2, _translate("FormCreateRegister", "User-Password"))
        self.comboBox_operation.setItemText(0, _translate("FormCreateRegister", "="))
        self.comboBox_operation.setItemText(1, _translate("FormCreateRegister", ":="))
        self.comboBox_operation.setItemText(2, _translate("FormCreateRegister", "=="))
        self.comboBox_operation.setItemText(3, _translate("FormCreateRegister", "+="))
        self.comboBox_operation.setItemText(4, _translate("FormCreateRegister", "!="))
        self.comboBox_operation.setItemText(5, _translate("FormCreateRegister", ">"))
        self.comboBox_operation.setItemText(6, _translate("FormCreateRegister", ">="))
        self.comboBox_operation.setItemText(7, _translate("FormCreateRegister", "<"))
        self.comboBox_operation.setItemText(8, _translate("FormCreateRegister", "<="))
        self.comboBox_operation.setItemText(9, _translate("FormCreateRegister", "=~"))
        self.comboBox_operation.setItemText(10, _translate("FormCreateRegister", "!~"))
        self.comboBox_operation.setItemText(11, _translate("FormCreateRegister", "=*"))
        self.comboBox_operation.setItemText(12, _translate("FormCreateRegister", "!*"))

